# Preparação dos Dados

### Importação das Bibliotecas

In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

import plotly.graph_objects as go
import plotly.express as px

# plot parameters
%matplotlib inline
plt.rcParams['font.size'] = 14
plt.rcParams['figure.figsize'] = (9, 5)
plt.rcParams['figure.facecolor'] = '#00000000'

from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import pickle
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import cross_val_score

In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

import plotly.graph_objects as go
import plotly.express as px

# plot parameters
%matplotlib inline
plt.rcParams['font.size'] = 14
plt.rcParams['figure.figsize'] = (9, 5)
plt.rcParams['figure.facecolor'] = '#00000000'

from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import pickle
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import cross_val_score

### Leitura dos Dados

In [103]:
df_ini  = pd.read_csv("data/dados.csv")
df_prep = pd.read_csv("data/dados_prep.csv")
df_ind  = pd.read_csv("data/dados_prep_index.csv")

In [104]:
df_prep.columns

Index(['Order_Quantity', 'Critical_Ship_Mode', 'High_Ship_Mode',
       'Low_Ship_Mode', 'Medium_Ship_Mode', 'NotSfd_Ship_Mode',
       'Regular_Ship_Mode', 'Express_Ship_Mode', 'Atlantic_Region',
       'NT_Region', 'Nunavut_Region', 'Ontario_Region', 'Prarie_Region',
       'West_Region', 'Consumer_Customer_Segment',
       'Corporate_Customer_Segment', 'HO_Customer_Segment',
       'SB_Customer_Segment', 'Furniture_Product_Category',
       'OF_Product_Category', 'Technology_Product_Category',
       'LB_Product_Container', 'MB_Product_Container', 'SB_Product_Container',
       'Sales', 'Profit'],
      dtype='object')

In [105]:
df_ini.columns

Index(['Order_ID', 'Order_Priority', 'Order_Quantity', 'Sales', 'Ship_Mode',
       'Profit', 'Customer_Name', 'Region', 'Customer_Segment',
       'Product_Category', 'Product_Sub-Category', 'Product_Name',
       'Product_Container'],
      dtype='object')

### Modelo de Predição para Order_Priority para o valor 'Not Specified''

In [106]:
df_esp     = df_ind.query(''' Order_Priority !='Not Specified' ''')

In [107]:
df_esp[['Order_Priority']].sample(5)

    Order_Priority
521            Low
10            High
27             Low
156            Low
374            Low

In [108]:
def order_pri(line):
    if line == 'Critical':
        return 1   
    elif line == 'High':
        return 2   
    elif line == 'Low':
        return 3   
    elif line == 'Medium':
        return 4

In [109]:
df_esp['Type_Order_Priority'] = df_esp['Order_Priority'].apply(lambda x: order_pri(x))

In [110]:
df_esp.sample(5)

,Order_ID,Order_Priority,Order_Quantity,Critical_Ship_Mode,High_Ship_Mode,Low_Ship_Mode,Medium_Ship_Mode,NotSfd_Ship_Mode,Regular_Ship_Mode,Express_Ship_Mode,...,SB_Customer_Segment,Furniture_Product_Category,OF_Product_Category,Technology_Product_Category,LB_Product_Container,MB_Product_Container,SB_Product_Container,Sales,Profit,Type_Order_Priority
634,48452,High,19,0,1,0,0,0,1,0,...,0,0,0,1,0,0,1,1781.1100,51.44,2
517,2279,Medium,39,0,0,0,1,0,1,0,...,0,0,1,0,0,0,1,845.9000,52.53,4
244,21091,High,32,0,1,0,0,0,0,1,...,0,0,1,0,0,0,1,270.7300,-54.57,2
586,4261,Critical,48,1,0,0,0,0,1,0,...,0,0,1,0,0,0,1,274.3800,-94.82,1
478,28836,High,50,0,1,0,0,0,1,0,...,0,0,0,1,0,0,1,8221.2935,2342.21,2

In [111]:
df_not_spec = df_ind.query(''' Order_Priority =='Not Specified' ''')

In [112]:
df_esp.columns

Index(['Order_ID', 'Order_Priority', 'Order_Quantity', 'Critical_Ship_Mode',
       'High_Ship_Mode', 'Low_Ship_Mode', 'Medium_Ship_Mode',
       'NotSfd_Ship_Mode', 'Regular_Ship_Mode', 'Express_Ship_Mode',
       'Atlantic_Region', 'NT_Region', 'Nunavut_Region', 'Ontario_Region',
       'Prarie_Region', 'West_Region', 'Consumer_Customer_Segment',
       'Corporate_Customer_Segment', 'HO_Customer_Segment',
       'SB_Customer_Segment', 'Furniture_Product_Category',
       'OF_Product_Category', 'Technology_Product_Category',
       'LB_Product_Container', 'MB_Product_Container', 'SB_Product_Container',
       'Sales', 'Profit', 'Type_Order_Priority'],
      dtype='object')

In [113]:
df = df_esp

In [114]:
X =  df.drop(['Order_ID','Profit', 'Order_Priority','Type_Order_Priority', ], axis = 1)
Y =  df['Type_Order_Priority']

In [115]:
seed = 1234
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = seed )

In [116]:
KNN_model = KNeighborsClassifier(n_neighbors=5)

In [117]:
KNN_model.fit(X_train, y_train)
KNN_prediction = KNN_model.predict(X_test)

In [118]:
print(accuracy_score(KNN_prediction, y_test))

0.19130434782608696

In [119]:
print(classification_report(KNN_prediction, y_test))

              precision    recall  f1-score   support

           1       0.30      0.20      0.24        41
           2       0.23      0.23      0.23        30
           3       0.16      0.18      0.17        28
           4       0.08      0.12      0.10        16

    accuracy                           0.19       115
   macro avg       0.19      0.18      0.18       115
weighted avg       0.21      0.19      0.20       115

### Execução com N-Modelos

In [120]:
models = []

models.append(("LogisticRegression",LogisticRegression()))
models.append(("SVC",SVC()))
models.append(("LinearSVC",LinearSVC()))
models.append(("KNeighbors",KNeighborsClassifier()))
models.append(("DecisionTree",DecisionTreeClassifier()))
models.append(("RandomForest",RandomForestClassifier()))
rf2 = RandomForestClassifier(n_estimators=100, criterion='gini',
                                max_depth=10, random_state=0, max_features=None)
models.append(("RandomForest2",rf2))
models.append(("MLPClassifier",MLPClassifier(solver='lbfgs', random_state=0)))


results = []
names = []
for name,model in models:
    result = cross_val_score(model, X,Y,  cv=3)
    names.append(name)
    results.append(result)

for i in range(len(names)):
    print(names[i],results[i].mean())

LogisticRegression 1.0
SVC 0.2404468440954043
LinearSVC 0.9340277777777778
KNeighbors 0.23519306282722516
DecisionTree 1.0
RandomForest 1.0
RandomForest2 1.0
MLPClassifier 0.374081951716114

### Execução com o Modelo que apresentou o melhor resultado

In [121]:
rf2 = RandomForestClassifier(n_estimators=100, criterion='gini',
                                max_depth=10, random_state=0, max_features=None)

In [122]:
rf2.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, max_features=None, random_state=0)

In [123]:
rf2_prediction = rf2.fit(X_train, y_train).predict(X_test)

In [124]:
print(accuracy_score(rf2_prediction, y_test))

1.0

In [125]:
print(classification_report(rf2_prediction, y_test))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        27
           2       1.00      1.00      1.00        31
           3       1.00      1.00      1.00        32
           4       1.00      1.00      1.00        25

    accuracy                           1.00       115
   macro avg       1.00      1.00      1.00       115
weighted avg       1.00      1.00      1.00       115

In [126]:
df_not_spec['Type_Order_Priority'] = df_not_spec['Order_Priority'].apply(lambda x: order_pri(x))

In [127]:
X =  df_not_spec.drop(['Order_ID','Profit', 'Order_Priority','Type_Order_Priority', ], axis = 1)

In [128]:
model = rf2.fit(X_train, y_train)

In [129]:
rf2_prediction = model.predict(X)

In [130]:
df_not_spec['Type_Order_Priority_Pred'] = rf2_prediction

In [131]:
df_not_spec.query(''' Type_Order_Priority_Pred == 4 ''')

,Order_ID,Order_Priority,Order_Quantity,Critical_Ship_Mode,High_Ship_Mode,Low_Ship_Mode,Medium_Ship_Mode,NotSfd_Ship_Mode,Regular_Ship_Mode,Express_Ship_Mode,...,Furniture_Product_Category,OF_Product_Category,Technology_Product_Category,LB_Product_Container,MB_Product_Container,SB_Product_Container,Sales,Profit,Type_Order_Priority,Type_Order_Priority_Pred
2,9127,Not Specified,7,0,0,0,0,1,0,1,...,0,1,0,1,0,0,2039.5600,-329.49,None,4
5,41696,Not Specified,45,0,0,0,0,1,0,1,...,0,1,0,1,0,0,237.2800,-2088.68,None,4
8,5988,Not Specified,40,0,0,0,0,1,0,1,...,0,0,1,1,0,0,19109.6100,-379.29,None,4
9,51073,Not Specified,17,0,0,0,0,1,0,1,...,1,0,0,1,0,0,2475.0800,958.80,None,4
11,32582,Not Specified,27,0,0,0,0,1,0,1,...,1,0,0,1,0,0,2780.8800,595.38,None,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,37862,Not Specified,27,0,0,0,0,1,1,0,...,0,1,0,0,0,1,1603.2700,452.49,None,4
715,2373,Not Specified,36,0,0,0,0,1,1,0,...,0,1,0,0,0,1,317.5900,-46.12,None,4
720,29318,Not Specified,34,0,0,0,0,1,1,0,...,0,0,1,0,0,1,3375.3075,562.13,None,4
725,56101,Not Specified,44,0,0,0,0,1,1,0,...,0,1,0,0,0,1,5347.1300,1886.41,None,4
728,1826,Not Specified,5,0,0,0,0,1,1,0,...,0,1,0,0,0,1,28.3200,-14.35,None,4

In [132]:
df_not_spec.sample(10)

,Order_ID,Order_Priority,Order_Quantity,Critical_Ship_Mode,High_Ship_Mode,Low_Ship_Mode,Medium_Ship_Mode,NotSfd_Ship_Mode,Regular_Ship_Mode,Express_Ship_Mode,...,Furniture_Product_Category,OF_Product_Category,Technology_Product_Category,LB_Product_Container,MB_Product_Container,SB_Product_Container,Sales,Profit,Type_Order_Priority,Type_Order_Priority_Pred
207,45059,Not Specified,39,0,0,0,0,1,0,1,...,0,1,0,0,0,1,3401.800,-508.87,None,4
133,13795,Not Specified,23,0,0,0,0,1,0,1,...,0,1,0,0,0,1,275.160,43.35,None,4
350,50336,Not Specified,9,0,0,0,0,1,1,0,...,0,1,0,0,0,1,58.980,-17.79,None,4
685,56708,Not Specified,36,0,0,0,0,1,1,0,...,0,1,0,0,0,1,407.170,-12.82,None,4
628,40608,Not Specified,39,0,0,0,0,1,1,0,...,0,1,0,0,0,1,223.790,-89.88,None,4
647,12228,Not Specified,30,0,0,0,0,1,1,0,...,0,0,1,0,0,1,5015.051,1090.43,None,4
251,6980,Not Specified,18,0,0,0,0,1,1,0,...,0,1,0,0,0,1,136.290,-77.28,None,4
76,21223,Not Specified,8,0,0,0,0,1,1,0,...,1,0,0,0,1,0,435.290,122.41,None,4
320,47520,Not Specified,47,0,0,0,0,1,1,0,...,0,1,0,0,0,1,925.300,257.31,None,4
696,15872,Not Specified,19,0,0,0,0,1,1,0,...,0,1,0,0,0,1,718.410,23.94,None,4

In [133]:
df = pd.DataFrame()
df     = pd.concat([df,df_not_spec]) 
df     = pd.concat([df,df_esp])

In [134]:
df.shape

(730, 30)

In [135]:
df.columns

Index(['Order_ID', 'Order_Priority', 'Order_Quantity', 'Critical_Ship_Mode',
       'High_Ship_Mode', 'Low_Ship_Mode', 'Medium_Ship_Mode',
       'NotSfd_Ship_Mode', 'Regular_Ship_Mode', 'Express_Ship_Mode',
       'Atlantic_Region', 'NT_Region', 'Nunavut_Region', 'Ontario_Region',
       'Prarie_Region', 'West_Region', 'Consumer_Customer_Segment',
       'Corporate_Customer_Segment', 'HO_Customer_Segment',
       'SB_Customer_Segment', 'Furniture_Product_Category',
       'OF_Product_Category', 'Technology_Product_Category',
       'LB_Product_Container', 'MB_Product_Container', 'SB_Product_Container',
       'Sales', 'Profit', 'Type_Order_Priority', 'Type_Order_Priority_Pred'],
      dtype='object')

In [136]:
df.sample(5)

,Order_ID,Order_Priority,Order_Quantity,Critical_Ship_Mode,High_Ship_Mode,Low_Ship_Mode,Medium_Ship_Mode,NotSfd_Ship_Mode,Regular_Ship_Mode,Express_Ship_Mode,...,Furniture_Product_Category,OF_Product_Category,Technology_Product_Category,LB_Product_Container,MB_Product_Container,SB_Product_Container,Sales,Profit,Type_Order_Priority,Type_Order_Priority_Pred
291,9792,Low,14,0,0,1,0,0,1,0,...,0,1,0,0,0,1,84.0900,-73.14,3,NaN
655,22053,Critical,32,1,0,0,0,0,1,0,...,0,1,0,0,0,1,563.0800,112.97,1,NaN
109,37281,Medium,25,0,0,0,1,0,1,0,...,0,0,1,0,1,0,453.2455,3.31,4,NaN
250,1792,Low,28,0,0,1,0,0,1,0,...,0,1,0,0,0,1,370.4800,-5.45,3,NaN
722,30016,Critical,8,1,0,0,0,0,1,0,...,0,0,1,0,0,1,754.6555,-212.55,1,NaN

In [137]:
def ord_prix(v):
    if v == 1 : 
        return 1
    elif v == 2 :
        return 2
    elif v == 3 :
        return 3
    elif v == 4 :
        return 4
    else:
        return 4

In [138]:
df['Type_Order_Prior'] = df['Type_Order_Priority'].apply(lambda x: ord_prix(x))

In [139]:
df.sample(5)

,Order_ID,Order_Priority,Order_Quantity,Critical_Ship_Mode,High_Ship_Mode,Low_Ship_Mode,Medium_Ship_Mode,NotSfd_Ship_Mode,Regular_Ship_Mode,Express_Ship_Mode,...,OF_Product_Category,Technology_Product_Category,LB_Product_Container,MB_Product_Container,SB_Product_Container,Sales,Profit,Type_Order_Priority,Type_Order_Priority_Pred,Type_Order_Prior
161,24965,Low,6,0,0,1,0,0,0,1,...,1,0,0,0,1,2528.49,580.15,3,NaN,3
663,36359,High,2,0,1,0,0,0,1,0,...,1,0,0,0,1,68.66,-29.60,2,NaN,2
365,5569,Not Specified,12,0,0,0,0,1,1,0,...,0,0,0,0,1,118.97,-0.06,None,4.0,4
618,32901,Critical,13,1,0,0,0,0,1,0,...,1,0,0,0,1,49.74,17.70,1,NaN,1
683,52487,Critical,17,1,0,0,0,0,1,0,...,1,0,0,0,1,124.06,15.74,1,NaN,1

In [140]:
df.columns

Index(['Order_ID', 'Order_Priority', 'Order_Quantity', 'Critical_Ship_Mode',
       'High_Ship_Mode', 'Low_Ship_Mode', 'Medium_Ship_Mode',
       'NotSfd_Ship_Mode', 'Regular_Ship_Mode', 'Express_Ship_Mode',
       'Atlantic_Region', 'NT_Region', 'Nunavut_Region', 'Ontario_Region',
       'Prarie_Region', 'West_Region', 'Consumer_Customer_Segment',
       'Corporate_Customer_Segment', 'HO_Customer_Segment',
       'SB_Customer_Segment', 'Furniture_Product_Category',
       'OF_Product_Category', 'Technology_Product_Category',
       'LB_Product_Container', 'MB_Product_Container', 'SB_Product_Container',
       'Sales', 'Profit', 'Type_Order_Priority', 'Type_Order_Priority_Pred',
       'Type_Order_Prior'],
      dtype='object')

In [150]:
df = df[[ 'Order_Quantity', 'Critical_Ship_Mode',
       'High_Ship_Mode', 'Low_Ship_Mode', 'Medium_Ship_Mode',
       'NotSfd_Ship_Mode', 'Regular_Ship_Mode', 'Express_Ship_Mode',
       'Atlantic_Region', 'NT_Region', 'Nunavut_Region', 'Ontario_Region',
       'Prarie_Region', 'West_Region', 'Consumer_Customer_Segment',
       'Corporate_Customer_Segment', 'HO_Customer_Segment',
       'SB_Customer_Segment', 'Furniture_Product_Category',
       'OF_Product_Category', 'Technology_Product_Category',
       'LB_Product_Container', 'MB_Product_Container', 'SB_Product_Container',
       'Sales', 'Profit', 'Type_Order_Prior']]

In [151]:
df[['Profit']].sample(5)

     Profit
97   -71.03
294  -70.04
107   14.35
583  -20.55
249   46.71

In [152]:
def target(line):
    line = float(line)
    if line >= 0 :
        return 1    
    else :
        return 0

In [153]:
df['Target'] = df['Profit'].apply(lambda x: target(x))

In [154]:
X =  df.drop(['Profit', 'Target'], axis = 1)
Y =  df['Target']

In [156]:
models = []

models.append(("LogisticRegression",LogisticRegression()))
models.append(("SVC",SVC()))
models.append(("LinearSVC",LinearSVC()))
models.append(("KNeighbors",KNeighborsClassifier()))
models.append(("DecisionTree",DecisionTreeClassifier()))
models.append(("RandomForest",RandomForestClassifier()))
rf2 = RandomForestClassifier(n_estimators=100, criterion='gini',
                                max_depth=10, random_state=0, max_features=None)
models.append(("RandomForest2",rf2))
models.append(("MLPClassifier",MLPClassifier(solver='lbfgs', random_state=0)))


results = []
names = []
for name,model in models:
    result = cross_val_score(model, X,Y,  cv=3)
    names.append(name)
    results.append(result)

for i in range(len(names)):
    print(names[i],results[i].mean())

LogisticRegression 0.6027176235130091
SVC 0.7069138051226697
LinearSVC 0.5699644696305292
KNeighbors 0.6986552429782545
DecisionTree 0.6944669320200588
RandomForest 0.7192426184533045
RandomForest2 0.7370359126582563
MLPClassifier 0.6149789741168005

In [157]:
rf2 = RandomForestClassifier(n_estimators=100, criterion='gini',
                                max_depth=10, random_state=0, max_features=None)

In [158]:
rf2.fit(X_train, y_train)
rf2_prediction = rf2.fit(X_train, y_train).predict(X_test)
print(accuracy_score(rf2_prediction, y_test))
print(classification_report(rf2_prediction, y_test))

1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        27
           2       1.00      1.00      1.00        31
           3       1.00      1.00      1.00        32
           4       1.00      1.00      1.00        25

    accuracy                           1.00       115
   macro avg       1.00      1.00      1.00       115
weighted avg       1.00      1.00      1.00       115